# Generated by Django 4.1.5 on 2023-01-24 13:54

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('sqft', models.IntegerField()),
                ('photo_main', models.FileField(upload_to=listings.models.image_path)),
                ('photo_1', models.FileField(blank=True, upload_to=listings.models.image_path)),
                ('photo_2', models.FileField(blank=True, upload_to=listings.models.image_path)),
                ('photo_3', models.FileField(blank=True, upload_to=listings.models.image_path)),
                ('photo_4', models.FileField(blank=True, upload_to=listings.models.image_path)),
                ('photo_5', models.FileField(blank=True, upload_to=listings.models.image_path)),
                ('photo_6', models.FileField(blank=True, upload_to=listings.models.image_path)),
                ('is_publushed', models.BooleanField(default=True)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
